tap 'homebrew/cask'

# highest priority
cask "brave-browser"
cask "superhuman"
cask "1password"
cask "todoist"

cask "alfred"
cask "appcleaner"
cask "atom"
cask "cyberduck"
cask "dbeaver-community"
cask "firefox"
cask "gpg-suite"
cask "iterm2"
cask "keybase"
cask "mplayerx"
cask "slack"
cask "spotify"
cask "tandem"
cask "the-unarchiver"
cask "whatsapp"

cask "microsoft-office"
cask "homebrew/cask-drivers/logitech-g-hub"
cask "homebrew/cask-fonts/font-meslo-for-powerline"

brew "ag"
brew "autojump"
brew "chruby"
brew "dos2unix"
brew "git"
brew "jsonpp"
brew "libgit2"
brew "libsodium"
brew "mas"
brew "mosh"
brew "mysql"
brew "node"
brew "openssh"
brew "postgresql"
brew "reattach-to-user-namespace"
brew "rectangle"
brew "ruby-install"
brew "sqlite"
brew "tmux"
brew "vim"
brew "vimpager"
brew "yarn"
brew "wget"
brew "zsh"
brew "zsh-completions"
